# Generated by Django 3.0.1 on 2020-04-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0002_tourist_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('phoneno', models.CharField(max_length=64)),
                ('room', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('price', models.CharField(max_length=64)),
            ],
        ),
    ]
