# Generated by Django 3.0.1 on 2020-04-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0003_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='city',
            field=models.CharField(default='puri', max_length=64),
        ),
    ]
