# Generated by Django 3.0.1 on 2020-05-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0004_bookings_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourist',
            old_name='passwordd',
            new_name='password',
        ),
        migrations.AddField(
            model_name='tourist',
            name='phone_no',
            field=models.CharField(default=0, max_length=64),
        ),
    ]
