# Generated by Django 3.0.1 on 2020-05-01 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0005_auto_20200501_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourist',
            name='password',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
