# Generated by Django 3.0.1 on 2020-07-21 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0008_auto_20200501_1002'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tourist',
        ),
    ]
